#!/usr/bin/env python3
"""
Archive a freshly-written cursor-feature-scout briefing.

Takes a markdown file (the newly filled-in briefing), copies it into the
briefings/ folder with a canonical date-stamped filename, and updates
briefings/INDEX.md with the new entry at the top.

Usage:
    python archive_briefing.py --input /tmp/briefing-draft.md \
        --week-start 2026-04-14 [--scout nverma14]

Filename convention:
    briefings/briefing-YYYY-MM-DD.md        (YYYY-MM-DD = week-start date)

Also maintains briefings/INDEX.md so readers can navigate all past briefings
without listing files.
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import shutil
import sys
from pathlib import Path

SKILL_ROOT = Path(__file__).resolve().parent.parent
BRIEFINGS_DIR = SKILL_ROOT / "briefings"
INDEX_PATH = BRIEFINGS_DIR / "INDEX.md"


def first_section_summary(md_text: str, heading: str = "TL;DR") -> str:
    """Extract the text under the first heading matching `heading` for the index."""
    lines = md_text.splitlines()
    captured: list[str] = []
    in_section = False
    for line in lines:
        h = re.match(r"^(#{1,6})\s+(.*)$", line)
        if h:
            if in_section:
                break
            if heading.lower() in h.group(2).strip().lower():
                in_section = True
                continue
        elif in_section:
            captured.append(line)
    text = "\n".join(captured).strip()
    # Keep bullets only, strip HTML comments and excessive blank lines
    text = re.sub(r"<!--.*?-->", "", text, flags=re.DOTALL).strip()
    # Truncate to ~400 chars for index
    if len(text) > 400:
        text = text[:400].rsplit(" ", 1)[0] + "…"
    return text


def rebuild_index() -> str:
    """Rebuild INDEX.md from every briefing file currently in briefings/."""
    briefings = sorted(
        (p for p in BRIEFINGS_DIR.glob("briefing-*.md") if p.is_file()),
        reverse=True,
    )
    lines = [
        "# Cursor Feature Scout — Briefing Index",
        "",
        "| Week of | Scout | TL;DR preview | File |",
        "|---|---|---|---|",
    ]
    for b in briefings:
        text = b.read_text(encoding="utf-8")
        date_match = re.search(r"briefing-(\d{4}-\d{2}-\d{2})\.md", b.name)
        week = date_match.group(1) if date_match else ""
        scout_match = re.search(r"Scout:\s*([^\s(·]+)", text)
        scout = scout_match.group(1).strip() if scout_match else ""
        preview = first_section_summary(text)
        preview_inline = " ".join(preview.splitlines())[:120].replace("|", "/") + "…"
        lines.append(f"| {week} | {scout} | {preview_inline} | [{b.name}](./{b.name}) |")
    lines.append("")
    lines.append(f"*Index auto-generated by archive_briefing.py on {dt.date.today().isoformat()}.*")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", type=Path, required=True,
                    help="Freshly written briefing markdown")
    ap.add_argument("--week-start", required=True,
                    help="YYYY-MM-DD (Monday of the week being reported on)")
    ap.add_argument("--scout", default="",
                    help="Scout user label (optional, for logging)")
    args = ap.parse_args()

    if not args.input.is_file():
        print(f"ERROR: input file not found: {args.input}", file=sys.stderr)
        return 2

    try:
        dt.date.fromisoformat(args.week_start)
    except ValueError:
        print("ERROR: --week-start must be YYYY-MM-DD", file=sys.stderr)
        return 2

    BRIEFINGS_DIR.mkdir(parents=True, exist_ok=True)
    dest = BRIEFINGS_DIR / f"briefing-{args.week_start}.md"
    shutil.copy(args.input, dest)

    # Rebuild index
    INDEX_PATH.write_text(rebuild_index(), encoding="utf-8")

    print(f"Archived: {dest}", file=sys.stderr)
    print(f"Index: {INDEX_PATH}", file=sys.stderr)
    if args.scout:
        print(f"Scout: {args.scout}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
